# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: feda9cff4341c7a80f1d2e385ee9d6994b5231d7e8f450201eee085cde9524986ea4d7b3b47da0fa8cc770c02ba987a8bd0c2fb82fc9aa72b0b0304f2fb033ac

test:
  secret_key_base: 9f24535dff21a0b2aad45a60ac234a5ba3ed951f498009c66db59b4ffdf77d0f3bb5646aa38e00969cd1cf29023ca395e4524611c6effffcc813af03973e9442

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
