# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6c0813c8c932d9fb99ff2affd182071708d14571fc96ee7482bd7b973bc27cda5ce746703710969943d38e2670162762aafc221e8cbc579d17300c8a3ec6e80

test:
  secret_key_base: 6899389f5b95bc6cfe29642220d6d36af708bd28161d277373552cced91c5bcc807efac6bcba97d477d57b1edc84bc187a5acb400e2d4449501e0554bc7268c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
